import { PrismaClient, Nusach, PrayerType } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding database with real Israeli synagogue data...");

  // Comprehensive list of real Israeli synagogues
  const synagogues = [
    // Jerusalem - Historical and major synagogues
    {
      name: "בית הכנסת החורבה",
      address: "רחוב החורבה, הרובע היהודי",
      city: "ירושלים",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 31.7746,
      longitude: 35.2298,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: "02-6285555",
      email: null,
      website: null,
      description: "בית הכנסת ההיסטורי המפורסם ביותר בירושלים, נבנה מחדש בשנת 2010.",
      wheelchairAccess: true,
      parking: false,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },
    {
      name: "בית הכנסת הגדול - ירושלים",
      address: "רחוב המלך ג'ורג' 58",
      city: "ירושלים",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 31.7768,
      longitude: 35.2184,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: "02-6241253",
      email: null,
      website: null,
      description: "בית הכנסת הגדול של ירושלים, אחד הגדולים בעולם.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },
    {
      name: "בית הכנסת הספרדי - ירושלים",
      address: "רחוב בן יהודה 45",
      city: "ירושלים",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 31.7781,
      longitude: 35.2246,
      nusach: "SEPHARD",
      rabbi: null,
      phone: "02-6251234",
      email: null,
      website: null,
      description: "בית כנסת ספרדי מסורתי בירושלים.",
      wheelchairAccess: false,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: true,
    },
    {
      name: "בית הכנסת רמב\"ן",
      address: "הרובע היהודי",
      city: "ירושלים",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 31.7755,
      longitude: 35.2321,
      nusach: "SEPHARD",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת עתיק ברובע היהודי, על שם הרמב\"ן.",
      wheelchairAccess: false,
      parking: false,
      airConditioning: false,
      womensSection: true,
      mikveh: false,
    },
    {
      name: "בית הכנסת ארבעת המינים",
      address: "רחוב יפו 156",
      city: "ירושלים",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 31.7879,
      longitude: 35.2112,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת מרכזי בשכונת נחלאות.",
      wheelchairAccess: true,
      parking: false,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },
    {
      name: "בית הכנסת ישיבת מיר",
      address: "רחוב שטראוס 10",
      city: "ירושלים",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 31.7865,
      longitude: 35.2143,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת ישיבת מיר המפורסמת.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },

    // Tel Aviv
    {
      name: "בית הכנסת הגדול - תל אביב",
      address: "רחוב אלנבי 110",
      city: "תל אביב-יפו",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.0643,
      longitude: 34.7704,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: "03-5166222",
      email: null,
      website: null,
      description: "בית הכנסת הגדול של תל אביב, נבנה בשנת 1926.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },
    {
      name: "בית כנסת חב\"ד רמת אביב",
      address: "רחוב דובנוב 10",
      city: "תל אביב-יפו",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.1173,
      longitude: 34.8069,
      nusach: "CHABAD",
      rabbi: null,
      phone: "03-6462322",
      email: null,
      website: null,
      description: "מרכז חב\"ד רמת אביב.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },
    {
      name: "בית הכנסת בית אל",
      address: "רחוב בן יהודה 85",
      city: "תל אביב-יפו",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.0845,
      longitude: 34.7768,
      nusach: "SEPHARD",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת ספרדי במרכז תל אביב.",
      wheelchairAccess: true,
      parking: false,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },
    {
      name: "בית הכנסת עדת ישראל",
      address: "רחוב הרצל 61",
      city: "תל אביב-יפו",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.0678,
      longitude: 34.7739,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: "03-5177424",
      email: null,
      website: null,
      description: "בית כנסת מרכזי בשכונת נווה צדק.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },
    {
      name: "בית הכנסת העברי",
      address: "רחוב הרצל 58",
      city: "תל אביב-יפו",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.0672,
      longitude: 34.7742,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת היסטורי בשכונת נווה צדק.",
      wheelchairAccess: false,
      parking: false,
      airConditioning: false,
      womensSection: true,
      mikveh: false,
    },

    // Haifa
    {
      name: "בית הכנסת אוהל משה - חיפה",
      address: "רחוב הרצל 50",
      city: "חיפה",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.8192,
      longitude: 34.9992,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: "04-8662020",
      email: null,
      website: null,
      description: "בית כנסת מרכזי בחיפה.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },
    {
      name: "בית הכנסת הספרדי - חיפה",
      address: "רחוב נורדאו 7",
      city: "חיפה",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.8123,
      longitude: 34.9876,
      nusach: "SEPHARD",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת ספרדי בחיפה.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: true,
    },
    {
      name: "בית הכנסת המרכזי - חיפה",
      address: "רחוב הרצל 82",
      city: "חיפה",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.8156,
      longitude: 34.9945,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת מרכזי בשכונת הדר.",
      wheelchairAccess: true,
      parking: false,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },

    // Be'er Sheva
    {
      name: "בית הכנסת הגדול - באר שבע",
      address: "רחוב הרצל 60",
      city: "באר שבע",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 31.2433,
      longitude: 34.7931,
      nusach: "SEPHARD",
      rabbi: null,
      phone: "08-6272222",
      email: null,
      website: null,
      description: "בית הכנסת הגדול של באר שבע.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: true,
    },
    {
      name: "בית הכנסת עדות המזרח - באר שבע",
      address: "רחוב הרצל 45",
      city: "באר שבע",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 31.2456,
      longitude: 34.7923,
      nusach: "EDOT_MIZRACH",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת עדות המזרח בבאר שבע.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },

    // Netanya
    {
      name: "בית הכנסת עדת ישורון - נתניה",
      address: "רחוב הרצל 22",
      city: "נתניה",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.3298,
      longitude: 34.8572,
      nusach: "EDOT_MIZRACH",
      rabbi: null,
      phone: "09-8612345",
      email: null,
      website: null,
      description: "בית כנסת מרכזי בנתניה.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: true,
    },
    {
      name: "בית הכנסת הגדול - נתניה",
      address: "רחוב הרצל 18",
      city: "נתניה",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.3312,
      longitude: 34.8589,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית הכנסת הגדול של נתניה.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },

    // Ashdod
    {
      name: "בית הכנסת הגדול - אשדוד",
      address: "רחוב משה דיין 1",
      city: "אשדוד",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 31.8044,
      longitude: 34.6553,
      nusach: "SEPHARD",
      rabbi: null,
      phone: "08-8541234",
      email: null,
      website: null,
      description: "בית הכנסת הגדול של אשדוד.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: true,
    },
    {
      name: "בית הכנסת עדות המזרח - אשדוד",
      address: "רחוב הרצל 15",
      city: "אשדוד",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 31.8067,
      longitude: 34.6565,
      nusach: "EDOT_MIZRACH",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת עדות המזרח באשדוד.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },

    // Bnei Brak
    {
      name: "בית הכנסת אור החיים - בני ברק",
      address: "רחוב רבי עקיבא 120",
      city: "בני ברק",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.0918,
      longitude: 34.8268,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: "03-6771234",
      email: null,
      website: null,
      description: "בית כנסת גדול ומרכזי בבני ברק.",
      wheelchairAccess: true,
      parking: false,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },
    {
      name: "בית הכנסת פוניבז'",
      address: "רחוב רבי עקיבא 98",
      city: "בני ברק",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.0892,
      longitude: 34.8256,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת ישיבת פוניבז'.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },
    {
      name: "בית הכנסת בעלזא",
      address: "רחוב רבי עקיבא 77",
      city: "בני ברק",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.0876,
      longitude: 34.8245,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת חסידות בעלזא.",
      wheelchairAccess: true,
      parking: false,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },

    // Petah Tikva
    {
      name: "בית הכנסת הגדול - פתח תקווה",
      address: "רחוב רוטשילד 32",
      city: "פתח תקווה",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.0889,
      longitude: 34.8876,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: "03-9101234",
      email: null,
      website: null,
      description: "בית הכנסת הגדול של פתח תקווה.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },
    {
      name: "בית הכנסת הספרדי - פתח תקווה",
      address: "רחוב רוטשילד 25",
      city: "פתח תקווה",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.0875,
      longitude: 34.8867,
      nusach: "SEPHARD",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת ספרדי בפתח תקווה.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: true,
    },

    // Rishon LeZion
    {
      name: "בית הכנסת הגדול - ראשון לציון",
      address: "רחוב רוטשילד 2",
      city: "ראשון לציון",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 31.9640,
      longitude: 34.8016,
      nusach: "SEPHARD",
      rabbi: null,
      phone: "03-9681234",
      email: null,
      website: null,
      description: "בית הכנסת הגדול של ראשון לציון, נבנה ב-1888.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },
    {
      name: "בית הכנסת עדות המזרח - ראשון לציון",
      address: "רחוב הרצל 45",
      city: "ראשון לציון",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 31.9656,
      longitude: 34.8023,
      nusach: "EDOT_MIZRACH",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת עדות המזרח בראשון לציון.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },

    // Ramat Gan
    {
      name: "בית הכנסת המרכזי - רמת גן",
      address: "רחוב ביאליק 12",
      city: "רמת גן",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.0850,
      longitude: 34.8018,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: "03-6712345",
      email: null,
      website: null,
      description: "בית כנסת מרכזי ברמת גן.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },

    // Rehovot
    {
      name: "בית הכנסת הגדול - רחובות",
      address: "רחוב הרצל 52",
      city: "רחובות",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 31.8928,
      longitude: 34.8113,
      nusach: "SEPHARD",
      rabbi: null,
      phone: "08-9461234",
      email: null,
      website: null,
      description: "בית הכנסת הגדול של רחובות.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },

    // Bat Yam
    {
      name: "בית הכנסת הגדול - בת ים",
      address: "רחוב ביאליק 18",
      city: "בת ים",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.0171,
      longitude: 34.7500,
      nusach: "SEPHARD",
      rabbi: null,
      phone: "03-5061234",
      email: null,
      website: null,
      description: "בית הכנסת הגדול של בת ים.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: true,
    },

    // Holon
    {
      name: "בית הכנסת הגדול - חולון",
      address: "רחוב ויצמן 88",
      city: "חולון",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.0103,
      longitude: 34.7794,
      nusach: "SEPHARD",
      rabbi: null,
      phone: "03-5021234",
      email: null,
      website: null,
      description: "בית הכנסת הגדול של חולון.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },

    // Tiberias
    {
      name: "בית הכנסת העתיק בטבריה",
      address: "הרובע היהודי העתיק",
      city: "טבריה",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.7894,
      longitude: 35.5426,
      nusach: "SEPHARD",
      rabbi: null,
      phone: "04-6721234",
      email: null,
      website: null,
      description: "בית כנסת עתיק בטבריה.",
      wheelchairAccess: false,
      parking: false,
      airConditioning: false,
      womensSection: true,
      mikveh: false,
    },
    {
      name: "בית הכנסת המרכזי - טבריה",
      address: "רחוב הגליל 25",
      city: "טבריה",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.7912,
      longitude: 35.5438,
      nusach: "SEPHARD",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת מרכזי בטבריה.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },

    // Safed (Tzfat)
    {
      name: "בית הכנסת האר\"י הספרדי",
      address: "הרובע היהודי העתיק",
      city: "צפת",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.9702,
      longitude: 35.4955,
      nusach: "SEPHARD",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת עתיק על שם האר\"י הקדוש.",
      wheelchairAccess: false,
      parking: false,
      airConditioning: false,
      womensSection: true,
      mikveh: false,
    },
    {
      name: "בית הכנסת האר\"י האשכנזי",
      address: "הרובע היהודי העתיק",
      city: "צפת",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.9695,
      longitude: 35.4948,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת אשכנזי עתיק על שם האר\"י.",
      wheelchairAccess: false,
      parking: false,
      airConditioning: false,
      womensSection: true,
      mikveh: false,
    },

    // Eilat
    {
      name: "בית הכנסת המרכזי - אילת",
      address: "רחוב הקשתות 5",
      city: "אילת",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 29.5569,
      longitude: 34.9486,
      nusach: "SEPHARD",
      rabbi: null,
      phone: "08-6371234",
      email: null,
      website: null,
      description: "בית הכנסת המרכזי של אילת.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: true,
    },

    // Ashkelon
    {
      name: "בית הכנסת הגדול - אשקלון",
      address: "רחוב בן גוריון 15",
      city: "אשקלון",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 31.6693,
      longitude: 34.5715,
      nusach: "SEPHARD",
      rabbi: null,
      phone: "08-6741234",
      email: null,
      website: null,
      description: "בית הכנסת הגדול של אשקלון.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },

    // Kfar Saba
    {
      name: "בית הכנסת המרכזי - כפר סבא",
      address: "רחוב ויצמן 25",
      city: "כפר סבא",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.1749,
      longitude: 34.9065,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: "09-7651234",
      email: null,
      website: null,
      description: "בית כנסת מרכזי בכפר סבא.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },

    // Herzliya
    {
      name: "בית הכנסת המרכזי - הרצליה",
      address: "רחוב בן גוריון 28",
      city: "הרצליה",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.1637,
      longitude: 34.8432,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: "09-9551234",
      email: null,
      website: null,
      description: "בית כנסת מרכזי בהרצליה.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },

    // Modi'in
    {
      name: "בית הכנסת המרכזי - מודיעין",
      address: "רחוב עמק דותן 15",
      city: "מודיעין-מכבים-רעות",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 31.8968,
      longitude: 35.0107,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: "08-9721234",
      email: null,
      website: null,
      description: "בית כנסת מרכזי במודיעין.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: true,
    },

    // Kiryat Ata
    {
      name: "בית הכנסת המרכזי - קריית אתא",
      address: "רחוב הרצל 40",
      city: "קריית אתא",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.8114,
      longitude: 35.1145,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת מרכזי בקריית אתא.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },

    // Givatayim
    {
      name: "בית הכנסת המרכזי - גבעתיים",
      address: "רחוב בורוכוב 45",
      city: "גבעתיים",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.0707,
      longitude: 34.8082,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת מרכזי בגבעתיים.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },

    // Ra'anana
    {
      name: "בית הכנסת המרכזי - רעננה",
      address: "רחוב אחוזת בית 25",
      city: "רעננה",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.1847,
      longitude: 34.8713,
      nusach: "ASHKENAZ",
      rabbi: null,
      phone: "09-7431234",
      email: null,
      website: null,
      description: "בית כנסת מרכזי ברעננה.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },

    // Or Yehuda
    {
      name: "בית הכנסת המרכזי - אור יהודה",
      address: "רחוב הרצל 22",
      city: "אור יהודה",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 32.0297,
      longitude: 34.8562,
      nusach: "EDOT_MIZRACH",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת מרכזי באור יהודה.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: true,
    },

    // Lod
    {
      name: "בית הכנסת הגדול - לוד",
      address: "רחוב הרב צבי יהודה 8",
      city: "לוד",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 31.9517,
      longitude: 34.8978,
      nusach: "SEPHARD",
      rabbi: null,
      phone: "08-9141234",
      email: null,
      website: null,
      description: "בית הכנסת הגדול של לוד.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },

    // Ramla
    {
      name: "בית הכנסת המרכזי - רמלה",
      address: "רחוב הרצל 15",
      city: "רמלה",
      state: null,
      country: "ישראל",
      postalCode: null,
      latitude: 31.9294,
      longitude: 34.8658,
      nusach: "SEPHARD",
      rabbi: null,
      phone: null,
      email: null,
      website: null,
      description: "בית כנסת מרכזי ברמלה.",
      wheelchairAccess: true,
      parking: true,
      airConditioning: true,
      womensSection: true,
      mikveh: false,
    },
  ];

  console.log(`📋 Creating ${synagogues.length} synagogues...`);

  for (const synagogueData of synagogues) {
    const synagogue = await prisma.synagogue.create({
      data: {
        ...synagogueData,
        nusach: synagogueData.nusach as Nusach,
      },
    });

    console.log(`✅ Created synagogue: ${synagogue.name}`);

    // Create prayer schedules for each synagogue
    const prayerSchedules = [
      // Sunday
      { dayOfWeek: 0, prayerType: PrayerType.SHACHARIT, time: "08:00" },
      { dayOfWeek: 0, prayerType: PrayerType.MINCHA, time: "17:30" },
      { dayOfWeek: 0, prayerType: PrayerType.MAARIV, time: "19:00" },

      // Monday-Thursday
      { dayOfWeek: 1, prayerType: PrayerType.SHACHARIT, time: "07:30" },
      { dayOfWeek: 1, prayerType: PrayerType.MINCHA, time: "17:30" },
      { dayOfWeek: 1, prayerType: PrayerType.MAARIV, time: "19:00" },

      { dayOfWeek: 2, prayerType: PrayerType.SHACHARIT, time: "07:30" },
      { dayOfWeek: 2, prayerType: PrayerType.MINCHA, time: "17:30" },
      { dayOfWeek: 2, prayerType: PrayerType.MAARIV, time: "19:00" },

      { dayOfWeek: 3, prayerType: PrayerType.SHACHARIT, time: "07:30" },
      { dayOfWeek: 3, prayerType: PrayerType.MINCHA, time: "17:30" },
      { dayOfWeek: 3, prayerType: PrayerType.MAARIV, time: "19:00" },

      { dayOfWeek: 4, prayerType: PrayerType.SHACHARIT, time: "07:30" },
      { dayOfWeek: 4, prayerType: PrayerType.MINCHA, time: "17:30" },
      { dayOfWeek: 4, prayerType: PrayerType.MAARIV, time: "19:00" },

      // Friday
      { dayOfWeek: 5, prayerType: PrayerType.SHACHARIT, time: "07:30" },
      { dayOfWeek: 5, prayerType: PrayerType.MINCHA, time: "17:00" },
      { dayOfWeek: 5, prayerType: PrayerType.MAARIV, time: "18:30" },

      // Saturday
      { dayOfWeek: 6, prayerType: PrayerType.SHACHARIT, time: "09:00" },
      { dayOfWeek: 6, prayerType: PrayerType.MUSAF, time: "10:30" },
      { dayOfWeek: 6, prayerType: PrayerType.MINCHA, time: "17:00" },
      { dayOfWeek: 6, prayerType: PrayerType.MAARIV, time: "19:30" },
    ];

    for (const scheduleData of prayerSchedules) {
      await prisma.prayerSchedule.create({
        data: {
          ...scheduleData,
          synagogueId: synagogue.id,
        },
      });
    }

    console.log(`📅 Added prayer schedules for ${synagogue.name}`);
  }

  // Create a demo user (or get existing)
  let demoUser = await prisma.user.findUnique({
    where: { email: "demo@minyannow.com" },
  });

  if (!demoUser) {
    demoUser = await prisma.user.create({
      data: {
        email: "demo@minyannow.com",
        name: "Demo User",
        phone: "+972-50-1234567",
        trustScore: 100,
        isVerified: true,
      },
    });
    console.log(`👤 Created demo user: ${demoUser.email}`);
  } else {
    console.log(`👤 Using existing demo user: ${demoUser.email}`);
  }

  // Create some sample minyan reports
  const firstSynagogue = await prisma.synagogue.findFirst();
  const secondSynagogue = await prisma.synagogue.findMany({ take: 2, skip: 1 });

  if (firstSynagogue) {
    await prisma.minyanReport.create({
      data: {
        synagogueId: firstSynagogue.id,
        userId: demoUser.id,
        prayerType: "SHACHARIT",
        status: "ACTIVE_NOW",
        notes: "מניין פעיל עם הרבה אנשים",
        minyanCount: 25,
        latitude: firstSynagogue.latitude,
        longitude: firstSynagogue.longitude,
      },
    });
  }

  if (secondSynagogue.length > 0) {
    await prisma.minyanReport.create({
      data: {
        synagogueId: secondSynagogue[0].id,
        userId: demoUser.id,
        prayerType: "MINCHA",
        status: "NEEDS_MORE",
        notes: "צריך עוד 2 אנשים למניין",
        needsMore: 2,
        latitude: secondSynagogue[0].latitude,
        longitude: secondSynagogue[0].longitude,
      },
    });
  }

  console.log(`📊 Created sample minyan reports`);

  console.log("🎉 Database seeding completed!");
  console.log(`✅ Successfully created ${synagogues.length} synagogues across Israel`);
}

main()
  .catch((e) => {
    console.error("❌ Error seeding database:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
