import { NextRequest, NextResponse } from "next/server";
import { PrismaClient, Nusach } from "@prisma/client";

const prisma = new PrismaClient();

// 50 פיקטיביים בתי כנסת ברחבי ישראל עם תמונות
const synagogues = [
  // ירושלים (10 בתי כנסת)
  {
    name: "בית הכנסת אור החיים",
    address: "רחוב יפו 45",
    city: "ירושלים",
    state: null,
    country: "ישראל",
    postalCode: "91000",
    latitude: 31.7683,
    longitude: 35.2137,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב דוד כהן",
    phone: "02-1234567",
    email: "info@or-haim.co.il",
    website: null,
    description: "בית כנסת מרכזי בקרבת השוק, פעיל כל השבוע עם מניינים רבים.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת שער השמים",
    address: "רחוב המלך ג'ורג' 12",
    city: "ירושלים",
    state: null,
    country: "ישראל",
    postalCode: "91001",
    latitude: 31.7768,
    longitude: 35.2184,
    nusach: "SEPHARD" as Nusach,
    rabbi: "הרב משה לוי",
    phone: "02-2345678",
    email: null,
    website: null,
    description: "בית כנסת ספרדי מסורתי עם ארכיטקטורה מרשימה.",
    wheelchairAccess: false,
    parking: false,
    airConditioning: true,
    womensSection: true,
    mikveh: true,
    photoUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת בית יעקב",
    address: "רחוב בן יהודה 78",
    city: "ירושלים",
    state: null,
    country: "ישראל",
    postalCode: "91002",
    latitude: 31.7820,
    longitude: 35.2170,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב אברהם שטרן",
    phone: "02-3456789",
    email: null,
    website: null,
    description: "בית כנסת אשכנזי עם קהילה פעילה וחמה.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת אוהל משה",
    address: "רחוב אגרון 25",
    city: "ירושלים",
    state: null,
    country: "ישראל",
    postalCode: "91003",
    latitude: 31.7700,
    longitude: 35.2200,
    nusach: "SEPHARD" as Nusach,
    rabbi: "הרב יצחק מזרחי",
    phone: "02-4567890",
    email: null,
    website: null,
    description: "בית כנסת ספרדי עם מסורת ארוכת שנים.",
    wheelchairAccess: false,
    parking: false,
    airConditioning: false,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת חב\"ד - הרובע היהודי",
    address: "רחוב היהודים 15",
    city: "ירושלים",
    state: null,
    country: "ישראל",
    postalCode: "91004",
    latitude: 31.7746,
    longitude: 35.2298,
    nusach: "CHABAD" as Nusach,
    rabbi: "הרב מנחם מנדל",
    phone: "02-5678901",
    email: "chabad@jerusalem.co.il",
    website: null,
    description: "בית כנסת חב\"ד פעיל עם מניינים רבים במהלך היום.",
    wheelchairAccess: true,
    parking: false,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת תורת חיים",
    address: "רחוב שטראוס 30",
    city: "ירושלים",
    state: null,
    country: "ישראל",
    postalCode: "91005",
    latitude: 31.7800,
    longitude: 35.2150,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב יעקב רוזן",
    phone: "02-6789012",
    email: null,
    website: null,
    description: "בית כנסת עם לימוד תורה יומיומי.",
    wheelchairAccess: false,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת עדות המזרח",
    address: "רחוב הנביאים 42",
    city: "ירושלים",
    state: null,
    country: "ישראל",
    postalCode: "91006",
    latitude: 31.7750,
    longitude: 35.2250,
    nusach: "EDOT_MIZRACH" as Nusach,
    rabbi: "הרב שלמה עמר",
    phone: "02-7890123",
    email: null,
    website: null,
    description: "בית כנסת עדות המזרח עם מסורת עשירה.",
    wheelchairAccess: true,
    parking: false,
    airConditioning: true,
    womensSection: true,
    mikveh: true,
    photoUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת שער ציון",
    address: "רחוב יפו 120",
    city: "ירושלים",
    state: null,
    country: "ישראל",
    postalCode: "91007",
    latitude: 31.7700,
    longitude: 35.2100,
    nusach: "SEPHARD" as Nusach,
    rabbi: "הרב דוד בן שימול",
    phone: "02-8901234",
    email: null,
    website: null,
    description: "בית כנסת ספרדי עם קהילה גדולה ופעילה.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת בית אל",
    address: "רחוב המלך דוד 55",
    city: "ירושלים",
    state: null,
    country: "ישראל",
    postalCode: "91008",
    latitude: 31.7720,
    longitude: 35.2220,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב יוסף גולדברג",
    phone: "02-9012345",
    email: null,
    website: null,
    description: "בית כנסת מרכזי עם מניינים רבים במהלך היום.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת תימני - ירושלים",
    address: "רחוב עזרא 8",
    city: "ירושלים",
    state: null,
    country: "ישראל",
    postalCode: "91009",
    latitude: 31.7780,
    longitude: 35.2280,
    nusach: "YEMENITE" as Nusach,
    rabbi: "הרב שלום תימני",
    phone: "02-0123456",
    email: null,
    website: null,
    description: "בית כנסת תימני עם מסורת ייחודית ונוסח מיוחד.",
    wheelchairAccess: false,
    parking: false,
    airConditioning: false,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
  },

  // תל אביב (8 בתי כנסת)
  {
    name: "בית הכנסת הגדול - תל אביב",
    address: "רחוב אלנבי 110",
    city: "תל אביב-יפו",
    state: null,
    country: "ישראל",
    postalCode: "65111",
    latitude: 32.0640,
    longitude: 34.7700,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב ישראל מאיר לאו",
    phone: "03-1234567",
    email: "info@great-synagogue.co.il",
    website: null,
    description: "בית הכנסת הגדול של תל אביב, אחד הגדולים בישראל.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת אוהל מועד",
    address: "רחוב רוטשילד 45",
    city: "תל אביב-יפו",
    state: null,
    country: "ישראל",
    postalCode: "65201",
    latitude: 32.0660,
    longitude: 34.7720,
    nusach: "SEPHARD" as Nusach,
    rabbi: "הרב משה עזרא",
    phone: "03-2345678",
    email: null,
    website: null,
    description: "בית כנסת ספרדי במרכז תל אביב עם קהילה פעילה.",
    wheelchairAccess: true,
    parking: false,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת חב\"ד - תל אביב",
    address: "רחוב דיזנגוף 90",
    city: "תל אביב-יפו",
    state: null,
    country: "ישראל",
    postalCode: "64332",
    latitude: 32.0800,
    longitude: 34.7750,
    nusach: "CHABAD" as Nusach,
    rabbi: "הרב יוסף יצחק",
    phone: "03-3456789",
    email: "chabad@telaviv.co.il",
    website: null,
    description: "בית כנסת חב\"ד פעיל עם מניינים רבים.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת בית יעקב - תל אביב",
    address: "רחוב בן יהודה 120",
    city: "תל אביב-יפו",
    state: null,
    country: "ישראל",
    postalCode: "63401",
    latitude: 32.0700,
    longitude: 34.7800,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב דוד כהן",
    phone: "03-4567890",
    email: null,
    website: null,
    description: "בית כנסת אשכנזי עם קהילה חמה ופעילה.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת עדות המזרח - תל אביב",
    address: "רחוב הרצל 35",
    city: "תל אביב-יפו",
    state: null,
    country: "ישראל",
    postalCode: "65201",
    latitude: 32.0650,
    longitude: 34.7680,
    nusach: "EDOT_MIZRACH" as Nusach,
    rabbi: "הרב אברהם מזרחי",
    phone: "03-5678901",
    email: null,
    website: null,
    description: "בית כנסת עדות המזרח עם מסורת עשירה.",
    wheelchairAccess: true,
    parking: false,
    airConditioning: true,
    womensSection: true,
    mikveh: true,
    photoUrl: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת תורת חיים - תל אביב",
    address: "רחוב נחום גולדמן 12",
    city: "תל אביב-יפו",
    state: null,
    country: "ישראל",
    postalCode: "62001",
    latitude: 32.0850,
    longitude: 34.7900,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב יעקב רוזן",
    phone: "03-6789012",
    email: null,
    website: null,
    description: "בית כנסת עם לימוד תורה יומיומי וקהילה פעילה.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת שער השמים - תל אביב",
    address: "רחוב אלנבי 85",
    city: "תל אביב-יפו",
    state: null,
    country: "ישראל",
    postalCode: "65111",
    latitude: 32.0620,
    longitude: 34.7680,
    nusach: "SEPHARD" as Nusach,
    rabbi: "הרב משה לוי",
    phone: "03-7890123",
    email: null,
    website: null,
    description: "בית כנסת ספרדי מסורתי עם ארכיטקטורה מרשימה.",
    wheelchairAccess: false,
    parking: false,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת בית אל - תל אביב",
    address: "רחוב רוטשילד 30",
    city: "תל אביב-יפו",
    state: null,
    country: "ישראל",
    postalCode: "65201",
    latitude: 32.0640,
    longitude: 34.7710,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב יוסף גולדברג",
    phone: "03-8901234",
    email: null,
    website: null,
    description: "בית כנסת מרכזי עם מניינים רבים במהלך היום.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
  },

  // חיפה (5 בתי כנסת)
  {
    name: "בית הכנסת הגדול - חיפה",
    address: "רחוב הרצל 55",
    city: "חיפה",
    state: null,
    country: "ישראל",
    postalCode: "31001",
    latitude: 32.8150,
    longitude: 34.9890,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב דוד כהן",
    phone: "04-1234567",
    email: null,
    website: null,
    description: "בית הכנסת הגדול של חיפה, אחד הגדולים בצפון.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת אוהל משה - חיפה",
    address: "רחוב הרצל 80",
    city: "חיפה",
    state: null,
    country: "ישראל",
    postalCode: "31002",
    latitude: 32.8200,
    longitude: 34.9900,
    nusach: "SEPHARD" as Nusach,
    rabbi: "הרב משה עזרא",
    phone: "04-2345678",
    email: null,
    website: null,
    description: "בית כנסת ספרדי עם קהילה פעילה וחמה.",
    wheelchairAccess: true,
    parking: false,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת חב\"ד - חיפה",
    address: "רחוב הרצל 100",
    city: "חיפה",
    state: null,
    country: "ישראל",
    postalCode: "31003",
    latitude: 32.8250,
    longitude: 34.9920,
    nusach: "CHABAD" as Nusach,
    rabbi: "הרב מנחם מנדל",
    phone: "04-3456789",
    email: "chabad@haifa.co.il",
    website: null,
    description: "בית כנסת חב\"ד פעיל עם מניינים רבים.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת בית יעקב - חיפה",
    address: "רחוב יפו 25",
    city: "חיפה",
    state: null,
    country: "ישראל",
    postalCode: "31004",
    latitude: 32.8100,
    longitude: 34.9850,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב אברהם שטרן",
    phone: "04-4567890",
    email: null,
    website: null,
    description: "בית כנסת אשכנזי עם קהילה חמה ופעילה.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת עדות המזרח - חיפה",
    address: "רחוב הרצל 120",
    city: "חיפה",
    state: null,
    country: "ישראל",
    postalCode: "31005",
    latitude: 32.8300,
    longitude: 34.9950,
    nusach: "EDOT_MIZRACH" as Nusach,
    rabbi: "הרב שלמה עמר",
    phone: "04-5678901",
    email: null,
    website: null,
    description: "בית כנסת עדות המזרח עם מסורת עשירה.",
    wheelchairAccess: true,
    parking: false,
    airConditioning: true,
    womensSection: true,
    mikveh: true,
    photoUrl: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
  },

  // באר שבע (4 בתי כנסת)
  {
    name: "בית הכנסת הגדול - באר שבע",
    address: "רחוב הרצל 60",
    city: "באר שבע",
    state: null,
    country: "ישראל",
    postalCode: "84100",
    latitude: 31.2430,
    longitude: 34.7910,
    nusach: "SEPHARD" as Nusach,
    rabbi: "הרב משה לוי",
    phone: "08-1234567",
    email: null,
    website: null,
    description: "בית הכנסת הגדול של באר שבע, אחד הגדולים בדרום.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת אוהל מועד - באר שבע",
    address: "רחוב הרצל 80",
    city: "באר שבע",
    state: null,
    country: "ישראל",
    postalCode: "84101",
    latitude: 31.2450,
    longitude: 34.7930,
    nusach: "SEPHARD" as Nusach,
    rabbi: "הרב יצחק מזרחי",
    phone: "08-2345678",
    email: null,
    website: null,
    description: "בית כנסת ספרדי עם קהילה פעילה וחמה.",
    wheelchairAccess: true,
    parking: false,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת חב\"ד - באר שבע",
    address: "רחוב הרצל 100",
    city: "באר שבע",
    state: null,
    country: "ישראל",
    postalCode: "84102",
    latitude: 31.2470,
    longitude: 34.7950,
    nusach: "CHABAD" as Nusach,
    rabbi: "הרב יוסף יצחק",
    phone: "08-3456789",
    email: "chabad@beersheva.co.il",
    website: null,
    description: "בית כנסת חב\"ד פעיל עם מניינים רבים.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת בית יעקב - באר שבע",
    address: "רחוב הרצל 120",
    city: "באר שבע",
    state: null,
    country: "ישראל",
    postalCode: "84103",
    latitude: 31.2490,
    longitude: 34.7970,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב דוד כהן",
    phone: "08-4567890",
    email: null,
    website: null,
    description: "בית כנסת אשכנזי עם קהילה חמה ופעילה.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
  },

  // ערים נוספות (23 בתי כנסת)
  {
    name: "בית הכנסת הגדול - נתניה",
    address: "רחוב הרצל 25",
    city: "נתניה",
    state: null,
    country: "ישראל",
    postalCode: "42201",
    latitude: 32.3330,
    longitude: 34.8570,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב יעקב רוזן",
    phone: "09-1234567",
    email: null,
    website: null,
    description: "בית הכנסת הגדול של נתניה.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת אוהל מועד - אשדוד",
    address: "רחוב הרצל 40",
    city: "אשדוד",
    state: null,
    country: "ישראל",
    postalCode: "77401",
    latitude: 31.8044,
    longitude: 34.6553,
    nusach: "SEPHARD" as Nusach,
    rabbi: "הרב משה עזרא",
    phone: "08-1234567",
    email: null,
    website: null,
    description: "בית כנסת ספרדי עם קהילה פעילה.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת חב\"ד - רמת גן",
    address: "רחוב ביאליק 15",
    city: "רמת גן",
    state: null,
    country: "ישראל",
    postalCode: "52201",
    latitude: 32.0820,
    longitude: 34.8100,
    nusach: "CHABAD" as Nusach,
    rabbi: "הרב מנחם מנדל",
    phone: "03-1234567",
    email: "chabad@ramatgan.co.il",
    website: null,
    description: "בית כנסת חב\"ד פעיל.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת בית יעקב - בני ברק",
    address: "רחוב רבי עקיבא 50",
    city: "בני ברק",
    state: null,
    country: "ישראל",
    postalCode: "51201",
    latitude: 32.0900,
    longitude: 34.8300,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב אברהם שטרן",
    phone: "03-1234567",
    email: null,
    website: null,
    description: "בית כנסת אשכנזי עם קהילה חמה.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: true,
    photoUrl: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת עדות המזרח - פתח תקווה",
    address: "רחוב רוטשילד 30",
    city: "פתח תקווה",
    state: null,
    country: "ישראל",
    postalCode: "49001",
    latitude: 32.0880,
    longitude: 34.8860,
    nusach: "EDOT_MIZRACH" as Nusach,
    rabbi: "הרב שלמה עמר",
    phone: "03-1234567",
    email: null,
    website: null,
    description: "בית כנסת עדות המזרח עם מסורת עשירה.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: true,
    photoUrl: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת תורת חיים - ראשון לציון",
    address: "רחוב הרצל 20",
    city: "ראשון לציון",
    state: null,
    country: "ישראל",
    postalCode: "75101",
    latitude: 31.9600,
    longitude: 34.8040,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב יעקב רוזן",
    phone: "03-1234567",
    email: null,
    website: null,
    description: "בית כנסת עם לימוד תורה יומיומי.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת שער השמים - רחובות",
    address: "רחוב הרצל 15",
    city: "רחובות",
    state: null,
    country: "ישראל",
    postalCode: "76100",
    latitude: 31.8930,
    longitude: 34.8080,
    nusach: "SEPHARD" as Nusach,
    rabbi: "הרב משה לוי",
    phone: "08-1234567",
    email: null,
    website: null,
    description: "בית כנסת ספרדי מסורתי.",
    wheelchairAccess: true,
    parking: false,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת בית אל - אשקלון",
    address: "רחוב הרצל 10",
    city: "אשקלון",
    state: null,
    country: "ישראל",
    postalCode: "78201",
    latitude: 31.6680,
    longitude: 34.5740,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב יוסף גולדברג",
    phone: "08-1234567",
    email: null,
    website: null,
    description: "בית כנסת מרכזי עם מניינים רבים.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת תימני - טבריה",
    address: "רחוב הרצל 5",
    city: "טבריה",
    state: null,
    country: "ישראל",
    postalCode: "14100",
    latitude: 32.7950,
    longitude: 35.5300,
    nusach: "YEMENITE" as Nusach,
    rabbi: "הרב שלום תימני",
    phone: "04-1234567",
    email: null,
    website: null,
    description: "בית כנסת תימני עם מסורת ייחודית.",
    wheelchairAccess: false,
    parking: false,
    airConditioning: false,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת אור החיים - צפת",
    address: "רחוב יפו 8",
    city: "צפת",
    state: null,
    country: "ישראל",
    postalCode: "13100",
    latitude: 32.9690,
    longitude: 35.4980,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב דוד כהן",
    phone: "04-1234567",
    email: null,
    website: null,
    description: "בית כנסת מרכזי בקרבת השוק.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת שער ציון - אילת",
    address: "רחוב הרצל 12",
    city: "אילת",
    state: null,
    country: "ישראל",
    postalCode: "88000",
    latitude: 29.5570,
    longitude: 34.9510,
    nusach: "SEPHARD" as Nusach,
    rabbi: "הרב דוד בן שימול",
    phone: "08-1234567",
    email: null,
    website: null,
    description: "בית כנסת ספרדי עם קהילה גדולה.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת בית יעקב - מודיעין",
    address: "רחוב הרצל 18",
    city: "מודיעין-מכבים-רעות",
    state: null,
    country: "ישראל",
    postalCode: "71700",
    latitude: 31.8980,
    longitude: 35.0080,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב אברהם שטרן",
    phone: "08-1234567",
    email: null,
    website: null,
    description: "בית כנסת אשכנזי עם קהילה חמה.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת אוהל מועד - נהריה",
    address: "רחוב הרצל 22",
    city: "נהריה",
    state: null,
    country: "ישראל",
    postalCode: "22300",
    latitude: 33.0080,
    longitude: 35.0980,
    nusach: "SEPHARD" as Nusach,
    rabbi: "הרב משה עזרא",
    phone: "04-1234567",
    email: null,
    website: null,
    description: "בית כנסת ספרדי עם קהילה פעילה.",
    wheelchairAccess: true,
    parking: false,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת חב\"ד - קריית אתא",
    address: "רחוב הרצל 30",
    city: "קריית אתא",
    state: null,
    country: "ישראל",
    postalCode: "28000",
    latitude: 32.8060,
    longitude: 35.1060,
    nusach: "CHABAD" as Nusach,
    rabbi: "הרב יוסף יצחק",
    phone: "04-1234567",
    email: "chabad@kiryat-ata.co.il",
    website: null,
    description: "בית כנסת חב\"ד פעיל.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת תורת חיים - גבעתיים",
    address: "רחוב ביאליק 25",
    city: "גבעתיים",
    state: null,
    country: "ישראל",
    postalCode: "53101",
    latitude: 32.0720,
    longitude: 34.8120,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב יעקב רוזן",
    phone: "03-1234567",
    email: null,
    website: null,
    description: "בית כנסת עם לימוד תורה יומיומי.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת עדות המזרח - חולון",
    address: "רחוב הרצל 35",
    city: "חולון",
    state: null,
    country: "ישראל",
    postalCode: "58301",
    latitude: 32.0100,
    longitude: 34.7790,
    nusach: "EDOT_MIZRACH" as Nusach,
    rabbi: "הרב אברהם מזרחי",
    phone: "03-1234567",
    email: null,
    website: null,
    description: "בית כנסת עדות המזרח עם מסורת עשירה.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: true,
    photoUrl: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת שער השמים - כפר סבא",
    address: "רחוב הרצל 28",
    city: "כפר סבא",
    state: null,
    country: "ישראל",
    postalCode: "44201",
    latitude: 32.1720,
    longitude: 34.9060,
    nusach: "SEPHARD" as Nusach,
    rabbi: "הרב משה לוי",
    phone: "09-1234567",
    email: null,
    website: null,
    description: "בית כנסת ספרדי מסורתי.",
    wheelchairAccess: true,
    parking: false,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת בית אל - רעננה",
    address: "רחוב הרצל 20",
    city: "רעננה",
    state: null,
    country: "ישראל",
    postalCode: "43101",
    latitude: 32.1840,
    longitude: 34.8720,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב יוסף גולדברג",
    phone: "09-1234567",
    email: null,
    website: null,
    description: "בית כנסת מרכזי עם מניינים רבים.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת תימני - בת ים",
    address: "רחוב הרצל 15",
    city: "בת ים",
    state: null,
    country: "ישראל",
    postalCode: "59101",
    latitude: 32.0190,
    longitude: 34.7500,
    nusach: "YEMENITE" as Nusach,
    rabbi: "הרב שלום תימני",
    phone: "03-1234567",
    email: null,
    website: null,
    description: "בית כנסת תימני עם מסורת ייחודית.",
    wheelchairAccess: false,
    parking: false,
    airConditioning: false,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת אור החיים - הרצליה",
    address: "רחוב הרצל 40",
    city: "הרצליה",
    state: null,
    country: "ישראל",
    postalCode: "46101",
    latitude: 32.1660,
    longitude: 34.8440,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב דוד כהן",
    phone: "09-1234567",
    email: null,
    website: null,
    description: "בית כנסת מרכזי בקרבת השוק.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת שער ציון - לוד",
    address: "רחוב הרצל 25",
    city: "לוד",
    state: null,
    country: "ישראל",
    postalCode: "71100",
    latitude: 31.9510,
    longitude: 34.8880,
    nusach: "SEPHARD" as Nusach,
    rabbi: "הרב דוד בן שימול",
    phone: "08-1234567",
    email: null,
    website: null,
    description: "בית כנסת ספרדי עם קהילה גדולה.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת בית יעקב - רמלה",
    address: "רחוב הרצל 18",
    city: "רמלה",
    state: null,
    country: "ישראל",
    postalCode: "72100",
    latitude: 31.9250,
    longitude: 34.8660,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב אברהם שטרן",
    phone: "08-1234567",
    email: null,
    website: null,
    description: "בית כנסת אשכנזי עם קהילה חמה.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת אוהל מועד - קריית גת",
    address: "רחוב הרצל 12",
    city: "קריית גת",
    state: null,
    country: "ישראל",
    postalCode: "82100",
    latitude: 31.6100,
    longitude: 34.7640,
    nusach: "SEPHARD" as Nusach,
    rabbi: "הרב משה עזרא",
    phone: "08-1234567",
    email: null,
    website: null,
    description: "בית כנסת ספרדי עם קהילה פעילה.",
    wheelchairAccess: true,
    parking: false,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת חב\"ד - קריית שמונה",
    address: "רחוב הרצל 8",
    city: "קריית שמונה",
    state: null,
    country: "ישראל",
    postalCode: "11000",
    latitude: 33.2070,
    longitude: 35.5700,
    nusach: "CHABAD" as Nusach,
    rabbi: "הרב מנחם מנדל",
    phone: "04-1234567",
    email: "chabad@kiryat-shemona.co.il",
    website: null,
    description: "בית כנסת חב\"ד פעיל.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת תורת חיים - עכו",
    address: "רחוב הרצל 5",
    city: "עכו",
    state: null,
    country: "ישראל",
    postalCode: "24100",
    latitude: 32.9280,
    longitude: 35.0810,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב יעקב רוזן",
    phone: "04-1234567",
    email: null,
    website: null,
    description: "בית כנסת עם לימוד תורה יומיומי.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת עדות המזרח - זכרון יעקב",
    address: "רחוב הרצל 3",
    city: "זכרון יעקב",
    state: null,
    country: "ישראל",
    postalCode: "30900",
    latitude: 32.5690,
    longitude: 34.9500,
    nusach: "EDOT_MIZRACH" as Nusach,
    rabbi: "הרב אברהם מזרחי",
    phone: "04-1234567",
    email: null,
    website: null,
    description: "בית כנסת עדות המזרח עם מסורת עשירה.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: true,
    photoUrl: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת שער השמים - חדרה",
    address: "רחוב הרצל 2",
    city: "חדרה",
    state: null,
    country: "ישראל",
    postalCode: "38100",
    latitude: 32.4340,
    longitude: 34.9200,
    nusach: "SEPHARD" as Nusach,
    rabbi: "הרב משה לוי",
    phone: "04-1234567",
    email: null,
    website: null,
    description: "בית כנסת ספרדי מסורתי.",
    wheelchairAccess: true,
    parking: false,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
  },
  {
    name: "בית הכנסת בית אל - רמת השרון",
    address: "רחוב הרצל 1",
    city: "רמת השרון",
    state: null,
    country: "ישראל",
    postalCode: "47201",
    latitude: 32.1400,
    longitude: 34.8390,
    nusach: "ASHKENAZ" as Nusach,
    rabbi: "הרב יוסף גולדברג",
    phone: "03-1234567",
    email: null,
    website: null,
    description: "בית כנסת מרכזי עם מניינים רבים.",
    wheelchairAccess: true,
    parking: true,
    airConditioning: true,
    womensSection: true,
    mikveh: false,
    photoUrl: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
  },
];

export async function POST(request: NextRequest) {
  try {
    // Security: Only allow in development or with a secret token
    const authHeader = request.headers.get("authorization");
    const secretToken = process.env.SEED_SECRET_TOKEN;
    
    if (process.env.NODE_ENV === "production" && (!secretToken || authHeader !== `Bearer ${secretToken}`)) {
      return NextResponse.json(
        { error: "Unauthorized" },
        { status: 401 }
      );
    }

    console.log("🌱 Starting database seed...");

    let created = 0;
    let skipped = 0;
    const createdSynagogueIds: string[] = [];

    for (const synagogueData of synagogues) {
      try {
        // Check if synagogue already exists
        const existing = await prisma.synagogue.findFirst({
          where: {
            name: synagogueData.name,
            city: synagogueData.city,
          },
        });

        if (existing) {
          skipped++;
          continue;
        }

        // Create synagogue
        const { photoUrl, ...synagogueDataWithoutPhoto } = synagogueData;
        const synagogue = await prisma.synagogue.create({
          data: synagogueDataWithoutPhoto,
        });

        // Add photo if provided
        if (photoUrl) {
          await prisma.synagoguePhoto.create({
            data: {
              synagogueId: synagogue.id,
              url: photoUrl,
              caption: `${synagogue.name} - תמונה`,
              isPrimary: true,
            },
          });
        }

        created++;
        createdSynagogueIds.push(synagogue.id);
      } catch (error: unknown) {
        if (error && typeof error === "object" && "code" in error && error.code === "P2002") {
          skipped++;
        } else {
          console.error(`Error creating ${synagogueData.name}:`, error);
        }
      }
    }

    const total = await prisma.synagogue.count();

    return NextResponse.json({
      success: true,
      message: "Database seeded successfully",
      created,
      skipped,
      total,
      synagogues: createdSynagogueIds,
    });
  } catch (error) {
    console.error("Error seeding database:", error);
    return NextResponse.json(
      { error: "Failed to seed database", details: String(error) },
      { status: 500 }
    );
  } finally {
    await prisma.$disconnect();
  }
}
